# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-30 13:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(blank=True, db_index=True, max_length=35, unique=True, verbose_name='Meeting Ref. No')),
                ('meeting_type', models.CharField(blank=True, choices=[(b'Finance', b'Finance'), (b'MANCO', b'MANCO'), (b'Project Team Leaders', b'Project Team Leaders')], db_index=True, max_length=50, null=True, verbose_name='Meeting Type')),
                ('pub_date', models.DateTimeField(verbose_name=b'Published Date')),
                ('date_from', models.DateTimeField(verbose_name=b'date from')),
                ('date_to', models.DateTimeField(verbose_name=b'date_to')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_status', models.CharField(max_length=200)),
                ('item_description', models.CharField(max_length=200)),
                ('item_due_date', models.DateTimeField(verbose_name=b'due date')),
                ('item_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting')),
            ],
        ),
    ]
